import type { Config } from './config';
import type {
  BiomeProvider,
  ConvergenceInfo,
  SkyState,
  TerrainProvider,
  TerrainSample,
  ThermalInfo,
  Vec3,
  WaveInfo,
  WindField,
  WindSample,
} from './types';
import { AirKind } from './types';
import { clamp, clamp01, distSqToSegmentXZ, smoothstep, TAU } from './math';
import { curl2, fbm3, makeRng, valueNoise2 } from './noise';

/**
 * THE ATMOSPHERE.
 *
 * Every flight game before this one treats air as empty space you move
 * through. This file is the argument that air is a *place* — structured,
 * legible, and made entirely out of the ground beneath it and the sun above.
 *
 * Seven kinds of air, and not one of them is sprinkled on by a designer:
 *
 *   thermal      a column over ground that has banked the sun's heat
 *   ridge        wind deflected up a windward face
 *   wave         a standing train downwind of a long ridge across the wind
 *   rotor        the tumbling wreckage underneath that wave
 *   convergence  a line where two air masses meet
 *   sink         where all of the above has to come back down
 *   still        the rest of the world
 *
 * Move the range and the wave moves. Shade the ground and the thermal dies.
 * Wait until dark and the thermals go entirely, and the wave — which never
 * needed the sun — gets *better*.
 *
 * PERFORMANCE. sample() is called several thousand times a frame: once for
 * the bird, once per companion, and once for every wind ribbon the renderer
 * is advecting. It allocates nothing, buckets thermals into a uniform grid,
 * and early-outs on squared distance before it touches an exp().
 */

// ====================================================================
// tuning that is about *shape* rather than feel — the feel knobs live in
// config.ts, these are the proportions that make the shapes read right.
// ====================================================================

/** Height (m) below which surface friction starts killing the wind. Real air
 *  slows near the ground, which is why ridge soaring close in feels different
 *  from cruising: you are in slower, rougher air. */
const SURFACE_LAYER = 120;
/** Fraction of the free-stream wind that survives right at the surface. */
const SURFACE_FRICTION = 0.35;

/** Radii at which a thermal's compensating sink ring begins and ends. Air
 *  going up in the middle has to come down somewhere, and it comes down
 *  immediately around the outside — which is exactly why leaving a thermal
 *  costs you and why centring feels like threading a needle. */
const SINK_RING_INNER = 1.35;
const SINK_RING_OUTER = 2.4;
/** Beyond this many radii a thermal contributes nothing. Squared for the
 *  early-out in the hot loop. */
const THERMAL_CUTOFF = SINK_RING_OUTER + 0.35;
const THERMAL_CUTOFF2 = THERMAL_CUTOFF * THERMAL_CUTOFF;

/** Grid cell (m) for the thermal spatial bucket. About two big thermal
 *  diameters — small enough to cull hard, large enough that a sample only
 *  ever has to look at one ring of neighbours. */
const BUCKET = 600;
const BUCKET_SPAN = 1; // cells to search either side

/** How far the focus point must move before the wave systems are re-scanned.
 *  Wave generators are enormous and nearly static, so this can be lazy. */
const WAVE_RESCAN_DISTANCE = 6000;
/** Coarse grid step (m) for the ridge-crest scan that finds wave generators. */
const CREST_STEP = 900;
/** Half-extent (m) of the crest scan around the focus. */
const CREST_RANGE = 26000;
const MAX_WAVES = 5;

/** Terrain gradient probe (m). Big enough to read a hillside rather than a
 *  boulder — ridge lift is generated by the shape of the hill, not its rocks. */
const SLOPE_PROBE = 22;

/** Below this |vy| nothing is reported as the dominant kind: the air is Still.
 *  Set too low and the HUD flickers between kinds in dead air. */
const KIND_THRESHOLD = 0.35;

// -------------------------------------------------------------- scratch
// Single-threaded and non-reentrant, so module-level scratch is safe and the
// hot path never touches the allocator.

const _terr: TerrainSample = { height: 0, nx: 0, ny: 1, nz: 0, slope: 0 };
const _curl = { x: 0, z: 0 };
const _windScratch: Vec3 = { x: 0, y: 0, z: 0 };

interface Contribution {
  vy: number;
  kind: AirKind;
  turb: number;
}
const _best: Contribution = { vy: 0, kind: AirKind.Still, turb: 0 };

/** A thermal, with the mutable lifecycle state the pool needs. */
interface LiveThermal extends ThermalInfo {
  /** Total seconds this incarnation will live. */
  lifespan: number;
  /** Cached ground heat at the source, 0..1. */
  heat: number;
  /** Bucket key this thermal is currently filed under. */
  cell: number;
}

export class AtmosphereField implements WindField {
  private readonly cfg: Config;
  private readonly terrain: TerrainProvider;
  private readonly biomes: BiomeProvider;
  private readonly rng: () => number;

  private readonly pool: LiveThermal[] = [];
  private readonly waveList: WaveInfo[] = [];
  private readonly convList: ConvergenceInfo[] = [];

  /** Uniform grid of thermal indices, rebuilt every update(). */
  private readonly buckets = new Map<number, number[]>();

  private focusX = 0;
  private focusZ = 0;
  private waveScanX = Infinity;
  private waveScanZ = Infinity;
  private time = 0;
  private activity = 0;
  private cloudBase = 1500;
  private nightGain = 1;

  /** Prevailing wind, cached per update rather than recomputed per sample. */
  private windX = 0;
  private windZ = 0;
  private windMag = 0;
  private windUnitX = 0;
  private windUnitZ = -1;

  constructor(cfg: Config, terrain: TerrainProvider, biomes: BiomeProvider) {
    this.cfg = cfg;
    this.terrain = terrain;
    this.biomes = biomes;
    this.rng = makeRng(cfg.seed * 7919 + 104729);

    for (let i = 0; i < cfg.thermalCount; i++) {
      const t: LiveThermal = {
        x: 0,
        z: 0,
        sourceX: 0,
        sourceZ: 0,
        radius: cfg.thermalRadius,
        strength: 0,
        base: 0,
        top: 0,
        life: 0,
        age: 0,
        tiltX: 0,
        tiltZ: 0,
        hasCloud: false,
        jitter: this.rng(),
        lifespan: cfg.thermalLifetime,
        heat: 0,
        cell: 0,
      };
      this.pool.push(t);
      this.reseed(t, true);
    }
    this.updateWind(0);
    this.buildConvergences();
  }

  // ================================================================ wind

  private updateWind(height: number): void {
    const c = this.cfg;
    // Speed grows with height and direction veers — both real, and together
    // they mean a climb changes where you are drifting to. Pilots plan around
    // exactly this.
    const km = Math.max(height, 0) / 1000;
    const mag = c.windSpeed * (1 + c.windShear * (km - 1));
    const dir = ((c.windDirDeg + c.windVeer * (km - 1)) * Math.PI) / 180;
    this.windUnitX = -Math.sin(dir);
    this.windUnitZ = -Math.cos(dir);
    this.windMag = Math.max(mag, 0);
    this.windX = this.windUnitX * this.windMag;
    this.windZ = this.windUnitZ * this.windMag;
  }

  prevailingAt(y: number, out: Vec3): Vec3 {
    const c = this.cfg;
    const km = Math.max(y, 0) / 1000;
    const mag = Math.max(c.windSpeed * (1 + c.windShear * (km - 1)), 0);
    const dir = ((c.windDirDeg + c.windVeer * (km - 1)) * Math.PI) / 180;
    out.x = -Math.sin(dir) * mag;
    out.y = 0;
    out.z = -Math.cos(dir) * mag;
    return out;
  }

  // ============================================================ thermals

  /**
   * Find this thermal a new home. Rejection-samples the ground for somewhere
   * hot: a thermal wants bare rock, desert or dry scrub, and will not root
   * over water or under a canopy. That single rule is what makes the colour
   * of the map and the shape of the lift the same information.
   */
  private reseed(t: LiveThermal, initial: boolean): void {
    const c = this.cfg;
    const rng = this.rng;
    let bestX = this.focusX;
    let bestZ = this.focusZ;
    let bestHeat = -1;

    for (let tries = 0; tries < 12; tries++) {
      // Bias new thermals UPWIND of the focus: they drift downwind as they
      // live, so seeding upwind means the player keeps flying into fresh air
      // rather than chasing columns that are always running away.
      const a = rng() * TAU;
      const r = 400 + rng() * (c.thermalHorizon - 400);
      const x = this.focusX + Math.cos(a) * r - this.windUnitX * r * 0.35;
      const z = this.focusZ + Math.sin(a) * r - this.windUnitZ * r * 0.35;
      const heat = this.biomes.heatAt(x, z);
      if (heat > bestHeat) {
        bestHeat = heat;
        bestX = x;
        bestZ = z;
      }
      if (heat > 0.75) break; // good enough — stop paying for samples
    }

    t.sourceX = bestX;
    t.sourceZ = bestZ;
    t.x = bestX;
    t.z = bestZ;
    t.heat = Math.max(bestHeat, 0);
    t.base = Math.max(this.terrain.heightAt(bestX, bestZ), this.terrain.waterLevel());
    t.jitter = rng();
    // Personality: ±45% radius, ±40% strength. A world where every column is
    // the same size is a world with nothing to learn.
    t.radius = c.thermalRadius * (0.55 + rng() * 0.9);
    t.strength = c.thermalStrength * (0.6 + rng() * 0.8);
    t.lifespan = c.thermalLifetime * (0.7 + rng() * 0.6);
    t.age = initial ? rng() * t.lifespan : 0;
    t.life = 0;
    this.retop(t);
  }

  /** Recompute the ceiling — it moves with cloudbase as the day develops. */
  private retop(t: LiveThermal): void {
    const c = this.cfg;
    const depth = Math.max(this.cloudBase - t.base, 180);
    t.top = t.base + depth * c.thermalTopFactor * (0.8 + t.jitter * 0.4);
  }

  private stepThermals(dt: number): void {
    const c = this.cfg;
    const fade = clamp01(c.thermalFadeFraction);
    for (const t of this.pool) {
      t.age += dt;

      // The column drifts downwind while the hot ground stays put. Once it
      // has been dragged too far from its source it is no longer being fed,
      // and it dies early — which is exactly what a real thermal does.
      const drift = c.thermalDrift * this.windMag * dt;
      t.x += this.windUnitX * drift;
      t.z += this.windUnitZ * drift;
      const dx = t.x - t.sourceX;
      const dz = t.z - t.sourceZ;
      const detached = dx * dx + dz * dz > (t.radius * 2.5) * (t.radius * 2.5);

      // Recycle when the life runs out, when it detaches, or when the focus
      // has wandered so far that this column is no longer anybody's problem.
      const fx = t.x - this.focusX;
      const fz = t.z - this.focusZ;
      const outOfRange = fx * fx + fz * fz > c.thermalHorizon * c.thermalHorizon * 1.4;
      if (t.age >= t.lifespan || detached || outOfRange) {
        this.reseed(t, false);
        continue;
      }

      const u = t.age / t.lifespan;
      // Fade in, hold, fade out. Smoothstep on both ends so a column never
      // switches on under you.
      t.life = Math.min(smoothstep(0, fade, u), 1 - smoothstep(1 - fade, 1, u));

      this.retop(t);

      // Downwind lean, in metres of offset per metre of height. This is the
      // reason you cannot hover over the hot spot: the lift at 1500 m is not
      // above the lift at 500 m, and following it is a genuine skill.
      const tilt = c.thermalTilt * clamp(this.windMag / 10, 0.2, 2.2);
      t.tiltX = this.windUnitX * tilt;
      t.tiltZ = this.windUnitZ * tilt;

      // A cumulus forms if there is enough depth to condense in, and if the
      // air is not too dry. Blue thermals — strong lift with no cloud to mark
      // it — happen over the hottest, driest ground, which is precisely where
      // the best lift is. That is the joke the desert plays on you at noon.
      const depth = t.top - t.base;
      t.hasCloud = depth > 420 && this.activity > 0.16 && t.jitter > t.heat * 0.55 - 0.05;
    }
  }

  private rebuildBuckets(): void {
    this.buckets.clear();
    for (let i = 0; i < this.pool.length; i++) {
      const t = this.pool[i];
      if (t.life <= 0.001) continue;
      const key = bucketKey(t.x, t.z);
      t.cell = key;
      let arr = this.buckets.get(key);
      if (!arr) {
        arr = [];
        this.buckets.set(key, arr);
      }
      arr.push(i);
    }
  }

  // ================================================================ wave

  /**
   * Find the ridges that can make wave.
   *
   * A wave generator is a long crest standing broadside to the wind: air
   * crossing it is thrown up, overshoots, and then oscillates downwind in a
   * standing train that can reach the stratosphere. The two things that
   * matter are *height* and *how square-on the crest is to the wind* — a
   * ridge running parallel to the wind makes nothing at all.
   */
  private scanWaves(): void {
    const c = this.cfg;
    if (!c.waveEnabled) return;
    this.waveList.length = 0;

    const wx = this.windUnitX;
    const wz = this.windUnitZ;
    // Across-wind unit vector — the direction a useful crest line runs.
    const ax = -wz;
    const az = wx;

    interface Cand {
      x: number;
      z: number;
      h: number;
      score: number;
    }
    const cands: Cand[] = [];

    for (let gz = -CREST_RANGE; gz <= CREST_RANGE; gz += CREST_STEP) {
      for (let gx = -CREST_RANGE; gx <= CREST_RANGE; gx += CREST_STEP) {
        const x = this.focusX + gx;
        const z = this.focusZ + gz;
        const h = this.terrain.heightAt(x, z);
        if (h < c.waveMinCrest) continue;

        // A crest is a local maximum ALONG the wind: higher than the ground
        // upwind of it and higher than the ground downwind of it.
        const step = CREST_STEP * 0.7;
        const up = this.terrain.heightAt(x - wx * step, z - wz * step);
        const dn = this.terrain.heightAt(x + wx * step, z + wz * step);
        if (h < up || h < dn) continue;

        // ...and it must be CONTINUOUS across the wind, or it is a peak, not
        // a ridge, and air just flows around it.
        const s1 = this.terrain.heightAt(x + ax * step, z + az * step);
        const s2 = this.terrain.heightAt(x - ax * step, z - az * step);
        const continuity = clamp01((Math.min(s1, s2) - c.waveMinCrest * 0.55) / (h - c.waveMinCrest * 0.55 + 1));

        const prominence = h - 0.5 * (up + dn);
        if (prominence < 90) continue;

        cands.push({
          x,
          z,
          h,
          score: prominence * (0.35 + 0.65 * continuity) * (h / c.waveMinCrest),
        });
      }
    }

    cands.sort((a, b) => b.score - a.score);

    for (const cd of cands) {
      if (this.waveList.length >= MAX_WAVES) break;
      // Keep the systems apart — two wave trains on top of each other is just
      // one loud wave train.
      let tooClose = false;
      for (const w of this.waveList) {
        const dx = w.crestX - cd.x;
        const dz = w.crestZ - cd.z;
        if (dx * dx + dz * dz < 9000 * 9000) {
          tooClose = true;
          break;
        }
      }
      if (tooClose) continue;

      const size = clamp01((cd.h - c.waveMinCrest) / c.waveMinCrest);
      this.waveList.push({
        crestX: cd.x,
        crestZ: cd.z,
        dirX: wx,
        dirZ: wz,
        // Wavelength grows with wind strength — stronger flow, longer waves.
        wavelength: c.waveLength * clamp(this.windMag / 11, 0.65, 1.6),
        amplitude: c.waveAmplitude * (0.55 + 0.75 * size),
        halfWidth: c.waveHalfWidth,
        halfLength: c.waveHalfLength * (0.7 + 0.6 * size),
        base: cd.h + c.waveBaseOffset,
        top: c.waveTop,
        crests: c.waveCrests,
      });
    }
  }

  // ========================================================= convergence

  /**
   * Convergence lines: places where two air masses run into each other and
   * the only way out is up. A sea breeze pushing inland against the
   * prevailing flow makes one that follows the coast; a big valley exhaling
   * in the afternoon makes another along its axis.
   *
   * Mechanically they are the best thing in the game, because you fly them in
   * a STRAIGHT LINE and climb the whole way. Circling is slow; a convergence
   * turns an afternoon into a hundred kilometres.
   */
  private buildConvergences(): void {
    const c = this.cfg;
    this.convList.length = 0;
    const rng = makeRng(c.seed * 31 + 7);
    const water = this.terrain.waterLevel();

    for (let i = 0; i < c.convergenceCount; i++) {
      // Walk a line across the map, steering it to follow either a coastline
      // or a valley floor — whichever the ground offers. Started from a
      // deterministic seed point so a world always grows the same lines.
      const a = (i / Math.max(c.convergenceCount, 1)) * TAU + rng() * 0.6;
      let x = Math.cos(a) * (5000 + rng() * 9000);
      let z = Math.sin(a) * (5000 + rng() * 9000);
      // Run roughly across the wind — convergence lines form where flows meet.
      let hx = -this.windUnitZ;
      let hz = this.windUnitX;
      if (rng() > 0.5) {
        hx = -hx;
        hz = -hz;
      }

      const points: Array<{ x: number; z: number }> = [{ x, z }];
      const SEG = 2600;
      for (let s = 0; s < 14; s++) {
        // Sample three headings and take the one that best tracks a shoreline
        // (ground closest to the waterline) or a valley (lowest ground).
        let bestScore = -Infinity;
        let bx = hx;
        let bz = hz;
        for (let k = -1; k <= 1; k++) {
          const ang = k * 0.34;
          const cs = Math.cos(ang);
          const sn = Math.sin(ang);
          const nx = hx * cs - hz * sn;
          const nz = hx * sn + hz * cs;
          const h = this.terrain.heightAt(x + nx * SEG, z + nz * SEG);
          // Prefer low ground; prefer being near the waterline most of all.
          const shore = -Math.abs(h - water) * 0.7;
          const low = -Math.max(h - water, 0) * 0.3;
          const score = shore + low - Math.abs(k) * 40; // mild straightness bonus
          if (score > bestScore) {
            bestScore = score;
            bx = nx;
            bz = nz;
          }
        }
        hx = bx;
        hz = bz;
        x += hx * SEG;
        z += hz * SEG;
        points.push({ x, z });
      }

      this.convList.push({
        points,
        strength: c.convergenceStrength * (0.75 + rng() * 0.5),
        halfWidth: c.convergenceHalfWidth * (0.8 + rng() * 0.5),
        base: water + 60,
        top: 2200,
        life: 0,
      });
    }
  }

  // ============================================================== update

  setFocus(x: number, z: number): void {
    this.focusX = x;
    this.focusZ = z;
  }

  update(dt: number, sky: SkyState): void {
    const c = this.cfg;
    this.time += dt;
    this.activity = sky.thermalActivity;
    this.cloudBase = sky.cloudBase;
    // Stable air waves better, and the air is at its most stable once the sun
    // stops stirring it. So the wave peaks exactly when everything else has
    // died — which is the entire late game.
    this.nightGain = 1 + (c.waveNightGain - 1) * (1 - clamp01(this.activity / 0.35));

    this.updateWind(1000);
    this.stepThermals(dt);
    this.rebuildBuckets();

    const dx = this.focusX - this.waveScanX;
    const dz = this.focusZ - this.waveScanZ;
    if (dx * dx + dz * dz > WAVE_RESCAN_DISTANCE * WAVE_RESCAN_DISTANCE) {
      this.waveScanX = this.focusX;
      this.waveScanZ = this.focusZ;
      this.scanWaves();
    }

    // Convergence lines develop through the afternoon and dissolve at dusk.
    const t = sky.t;
    const life =
      smoothstep(c.convergenceStartT, c.convergenceStartT + 0.09, t) *
      (1 - smoothstep(c.convergenceEndT - 0.08, c.convergenceEndT, t));
    for (const cv of this.convList) {
      cv.life = life;
      cv.top = Math.max(sky.cloudBase * c.convergenceTopFactor, cv.base + 300);
    }
  }

  thermals(): readonly ThermalInfo[] {
    return this.pool;
  }
  waves(): readonly WaveInfo[] {
    return this.waveList;
  }
  convergences(): readonly ConvergenceInfo[] {
    return this.convList;
  }

  // ============================================================== sample

  sample(x: number, y: number, z: number, out: WindSample): WindSample {
    const c = this.cfg;

    const ground = Math.max(this.terrain.heightAt(x, z), this.terrain.waterLevel());
    const agl = y - ground;

    // --- horizontal: the prevailing wind, slowed near the surface --------
    const km = Math.max(y, 0) / 1000;
    const mag = Math.max(c.windSpeed * (1 + c.windShear * (km - 1)), 0);
    const dir = ((c.windDirDeg + c.windVeer * (km - 1)) * Math.PI) / 180;
    const ux = -Math.sin(dir);
    const uz = -Math.cos(dir);
    const friction = SURFACE_FRICTION + (1 - SURFACE_FRICTION) * smoothstep(0, SURFACE_LAYER, agl);
    out.vx = ux * mag * friction;
    out.vz = uz * mag * friction;

    // Baseline: everything sinks a little. The tax on crossing country, and
    // the reason a glide has to be paid for.
    let vy = -c.ambientSink;
    const best = _best;
    best.vy = 0;
    best.kind = AirKind.Still;
    best.turb = 0;
    let turbulence = 0;

    // ---------------------------------------------------------- thermals
    {
      const cx = Math.floor(x / BUCKET);
      const cz = Math.floor(z / BUCKET);
      for (let bz = cz - BUCKET_SPAN; bz <= cz + BUCKET_SPAN; bz++) {
        for (let bx = cx - BUCKET_SPAN; bx <= cx + BUCKET_SPAN; bx++) {
          const arr = this.buckets.get(cellKey(bx, bz));
          if (!arr) continue;
          for (let i = 0; i < arr.length; i++) {
            const t = this.pool[arr[i]];
            if (t.life <= 0.001) continue;

            // The column leans downwind with height, so the centre we care
            // about is not the one on the ground.
            const dh = y - t.base;
            if (dh < -60 || y > t.top) continue;
            const ccx = t.x + t.tiltX * Math.max(dh, 0);
            const ccz = t.z + t.tiltZ * Math.max(dh, 0);
            const ex = x - ccx;
            const ez = z - ccz;
            const r2 = (ex * ex + ez * ez) / (t.radius * t.radius);
            if (r2 > THERMAL_CUTOFF2) continue;

            // Strength = the day's energy × this ground's heat × this
            // column's own life. Any of the three going to zero kills it.
            const power =
              t.strength * this.activity * (0.45 + 0.55 * t.heat) * t.life;
            if (power <= 0.001) continue;

            // Fade out toward the ceiling so a climb eases off rather than
            // hitting a lid, and taper near the ground where the column is
            // still gathering itself.
            const topFade = 1 - smoothstep(0.78, 1, dh / Math.max(t.top - t.base, 1));
            const baseFade = smoothstep(-60, 90, dh);
            const envelope = topFade * baseFade;
            if (envelope <= 0.001) continue;

            const r = Math.sqrt(r2);
            let contrib: number;
            if (r < SINK_RING_INNER) {
              // Gaussian core.
              contrib = power * Math.exp(-r2 * 1.35) * envelope;
            } else {
              // The compensating downdraught around the outside. Air that
              // went up in the middle is coming down out here, and this is
              // what makes a thermal something you have to stay inside of.
              const ring =
                Math.sin(
                  ((r - SINK_RING_INNER) / (SINK_RING_OUTER - SINK_RING_INNER)) * Math.PI,
                );
              contrib = -power * c.thermalSinkRing * Math.max(ring, 0) * envelope;
            }

            vy += contrib;
            // Roughest at the core edge, where the rising air is shearing
            // against the air that is not.
            const edge = Math.exp(-(r - 1) * (r - 1) * 3.2);
            const tb = c.thermalTurbulence * edge * t.life * clamp01(this.activity * 1.4);
            if (tb > turbulence) turbulence = tb;

            if (contrib > 0) {
              if (contrib > best.vy) {
                best.vy = contrib;
                best.kind = AirKind.Thermal;
                best.turb = tb;
              }
            } else if (-contrib > Math.abs(best.vy) && best.vy <= 0) {
              best.vy = contrib;
              best.kind = AirKind.Sink;
              best.turb = tb;
            }
          }
        }
      }
    }

    // ------------------------------------------------------------- ridge
    if (agl < c.ridgeCeiling && agl > -20) {
      this.terrain.sampleAt(x, z, _terr);
      // Gradient from the surface normal: the slope vector points uphill.
      const gx = -_terr.nx / Math.max(_terr.ny, 0.08);
      const gz = -_terr.nz / Math.max(_terr.ny, 0.08);
      const slope = Math.hypot(gx, gz);
      if (slope > c.ridgeMinSlope) {
        // How much of the wind is climbing the hill. Positive = windward.
        const upslope = ux * mag * gx + uz * mag * gz;
        const band = 1 - smoothstep(0, c.ridgeCeiling, agl);
        let contrib: number;
        let kind: AirKind;
        if (upslope > 0) {
          contrib = upslope * c.ridgeGain * band;
          kind = AirKind.Ridge;
        } else {
          // The lee. Air that went up the front comes down the back, and it
          // is the single most reliable way to lose a thousand metres.
          contrib = upslope * c.ridgeLeeSink * band * c.leeSinkGain;
          kind = AirKind.Sink;
        }
        vy += contrib;
        const tb = clamp01(slope * 0.6) * (upslope > 0 ? 0.22 : 0.5) * band;
        if (tb > turbulence) turbulence = tb;
        if (Math.abs(contrib) > Math.abs(best.vy)) {
          best.vy = contrib;
          best.kind = kind;
          best.turb = tb;
        }
      }
    }

    // -------------------------------------------------------------- wave
    for (let i = 0; i < this.waveList.length; i++) {
      const w = this.waveList[i];
      const ex = x - w.crestX;
      const ez = z - w.crestZ;
      // Downwind distance, and distance along the crest line.
      const along = ex * w.dirX + ez * w.dirZ;
      if (along < 0) continue; // wave lives downwind of its generator only
      const across = ex * -w.dirZ + ez * w.dirX;
      if (Math.abs(across) > w.halfLength) continue;

      const span = w.wavelength * w.crests;
      if (along > span) continue;

      const rotorTop = w.base;
      const rotorBottom = w.base - c.rotorDepth;

      // Envelope: fades out along the crest and decays with each successive
      // crest downwind. The first wave is always the best one.
      const alongFade = 1 - smoothstep(w.halfLength * 0.55, w.halfLength, Math.abs(across));
      const decay = 1 - smoothstep(0, span, along);
      const env = alongFade * decay;
      if (env <= 0.001) continue;

      if (y >= w.base && y <= w.top) {
        // The wave proper: a clean standing sinusoid. Lift on the upwind face
        // of each crest, sink on the downwind face — and the sink is exactly
        // as strong as the lift, which is why crossing a wave system the
        // wrong way is punishing and crossing it the right way is a gift.
        const phase = (along / w.wavelength) * TAU;
        const heightFade =
          smoothstep(w.base, w.base + 260, y) * (1 - smoothstep(w.top * 0.82, w.top, y));
        const contrib = Math.cos(phase) * w.amplitude * env * heightFade * this.nightGain;
        vy += contrib;
        // Wave is glassy. Reporting near-zero turbulence here is a tell the
        // player learns to trust before any instrument tells them.
        if (Math.abs(contrib) > Math.abs(best.vy)) {
          best.vy = contrib;
          best.kind = contrib > 0 ? AirKind.Wave : AirKind.Sink;
          best.turb = 0.02;
        }
      } else if (y < rotorTop && y > rotorBottom && along < w.wavelength * 1.6) {
        // Rotor: the wreckage under the first crest. Violent, tumbling, and
        // usually the only door into the wave above it.
        const depthFade =
          smoothstep(rotorBottom, rotorBottom + 140, y) * (1 - smoothstep(rotorTop - 120, rotorTop, y));
        const n = fbm3(x * 0.0016, y * 0.0022, z * 0.0016 + this.time * 0.05, this.cfg.seed + 991, 3);
        const contrib = n * 2 * c.rotorStrength * env * depthFade;
        vy += contrib;
        const tb = c.rotorTurbulence * env * depthFade;
        if (tb > turbulence) turbulence = tb;
        if (Math.abs(contrib) > Math.abs(best.vy)) {
          best.vy = contrib;
          best.kind = AirKind.Rotor;
          best.turb = tb;
        }
      }
    }

    // ------------------------------------------------------- convergence
    for (let i = 0; i < this.convList.length; i++) {
      const cv = this.convList[i];
      if (cv.life <= 0.001) continue;
      if (y < cv.base - 40 || y > cv.top) continue;

      let bestD2 = Infinity;
      const pts = cv.points;
      for (let p = 0; p + 1 < pts.length; p++) {
        const a = pts[p];
        const b = pts[p + 1];
        // Cheap reject: if both endpoints are far, the segment is far.
        const ma = (a.x - x) * (a.x - x) + (a.z - z) * (a.z - z);
        const mb = (b.x - x) * (b.x - x) + (b.z - z) * (b.z - z);
        const reach = (cv.halfWidth + 2800) * (cv.halfWidth + 2800);
        if (ma > reach && mb > reach) continue;
        const r = distSqToSegmentXZ(x, z, a.x, a.z, b.x, b.z);
        if (r.d2 < bestD2) bestD2 = r.d2;
      }
      if (bestD2 === Infinity) continue;
      const d = Math.sqrt(bestD2);
      if (d > cv.halfWidth * 1.6) continue;

      const across = 1 - smoothstep(cv.halfWidth * 0.5, cv.halfWidth * 1.6, d);
      const heightFade =
        smoothstep(cv.base - 40, cv.base + 160, y) * (1 - smoothstep(cv.top * 0.8, cv.top, y));
      const contrib = cv.strength * cv.life * across * heightFade;
      if (contrib <= 0.001) continue;
      vy += contrib;
      const tb = 0.16 * across;
      if (tb > turbulence) turbulence = tb;
      if (contrib > Math.abs(best.vy)) {
        best.vy = contrib;
        best.kind = AirKind.Convergence;
        best.turb = tb;
      }
    }

    // ------------------------------------------------------------- gusts
    // Divergence-free swirl, so nothing appears or vanishes — it just makes
    // the air feel alive rather than laminar. Texture only; never dominant.
    {
      const s = 1 / c.gustScale;
      const tt = this.time * c.gustSpeed;
      curl2(x * s + tt, z * s - tt * 0.6, c.seed + 313, 0.6, _curl);
      out.vx += _curl.x * c.gustStrength;
      out.vz += _curl.z * c.gustStrength;
      const gv =
        (valueNoise2(x * s * 1.7 + tt * 1.3, z * s * 1.7 - tt, c.seed + 577) - 0.5) *
        2 *
        c.gustStrength *
        0.55;
      vy += gv;
      const gt = Math.abs(gv) * 0.12;
      if (gt > turbulence) turbulence = gt;
    }

    out.vy = vy;
    out.turbulence = clamp01(turbulence);

    if (Math.abs(best.vy) < KIND_THRESHOLD) {
      out.kind = AirKind.Still;
      out.intensity = 0;
    } else {
      out.kind = best.kind;
      // Normalised against a strong-but-not-absurd 6 m/s, so the HUD and the
      // ribbon brightness saturate on genuinely good air rather than on the
      // one freak core in the world.
      out.intensity = clamp01(Math.abs(best.vy) / 6);
    }
    void _windScratch;
    return out;
  }
}

// ------------------------------------------------------------- bucketing

const cellKey = (cx: number, cz: number): number => (cx & 0xffff) * 65536 + (cz & 0xffff);
const bucketKey = (x: number, z: number): number =>
  cellKey(Math.floor(x / BUCKET), Math.floor(z / BUCKET));

// --------------------------------------------------------- presentation

/**
 * The palette the whole visual language of the air is built from. Linear RGB,
 * because everything downstream tonemaps. These are not arbitrary: warm for
 * air that is doing you a favour, cold for air that is taking from you, and
 * one genuinely otherworldly cyan for the wave, which should not look like
 * anything else in the game.
 */
const KIND_COLORS: Record<AirKind, { r: number; g: number; b: number }> = {
  [AirKind.Still]: { r: 0.3, g: 0.33, b: 0.38 },
  [AirKind.Thermal]: { r: 1.0, g: 0.72, b: 0.32 },
  [AirKind.Ridge]: { r: 0.72, g: 0.92, b: 0.66 },
  [AirKind.Wave]: { r: 0.56, g: 0.92, b: 1.0 },
  [AirKind.Rotor]: { r: 0.66, g: 0.52, b: 0.78 },
  [AirKind.Convergence]: { r: 1.0, g: 0.68, b: 0.76 },
  [AirKind.Sink]: { r: 0.34, g: 0.5, b: 0.72 },
};

export function airKindColor(kind: AirKind): { r: number; g: number; b: number } {
  return KIND_COLORS[kind] ?? KIND_COLORS[AirKind.Still];
}

const KIND_LABELS: Record<AirKind, string> = {
  [AirKind.Still]: '—',
  [AirKind.Thermal]: 'thermal',
  [AirKind.Ridge]: 'ridge lift',
  [AirKind.Wave]: 'wave',
  [AirKind.Rotor]: 'rotor',
  [AirKind.Convergence]: 'convergence',
  [AirKind.Sink]: 'sink',
};

export function airKindLabel(kind: AirKind): string {
  return KIND_LABELS[kind] ?? '—';
}
